#!/usr/bin/env bun
/**
 * The illustration label: an AI-generated placeholder must be labelled *on the page*.
 *
 *   bun test test/illustration-label.test.ts
 *
 * The plan's rule is that where no suitable public-domain photograph exists, an
 * AI-generated placeholder may be used — but it must be labelled on the page as an
 * illustration, not a photograph of the business, and recorded as such in the
 * bundle. The manifest half of that was already there ("AI-generated image used as
 * a fallback"); the page half was not: the caption element did not exist, so a
 * visitor saw an AI image presented as the shop.
 *
 * These tests pin both halves to one sentence, `illustrationLabel` in copy.ts:
 * the page renders it in a `<figcaption>` in normal flow (no hover, no JS), and the
 * build's compliance self-check refuses a page whose manifest records an
 * AI-generated image but which carries no such label.
 *
 * No filesystem, no network. Fixtures are fictional.
 */
import { expect, test } from "bun:test";

import { complianceChecks } from "../src/demo/build.ts";
import { composeCopy, illustrationLabel, isIllustrativeImage, profileFor } from "../src/demo/copy.ts";
import { resolveDelivery } from "../src/demo/delivery.ts";
import { resolveForm } from "../src/demo/forms.ts";
import { sourceImages } from "../src/demo/images.ts";
import { esc, renderIndex, type RenderContext } from "../src/demo/render.ts";
import type { BusinessRecord, ManifestImage } from "../src/demo/types.ts";

const BUSINESS_NAME = "Example Barber Shop";
const SLUG = "example-barber-shop";

const RECORD: BusinessRecord = {
  name: BUSINESS_NAME,
  category: "Barber shop",
  email: "shop@example-barber.ca",
  form_recipient: "site-sourced-311e0184@ctomail.io",
  form_delivery: "demo",
  form_provider: "formspark",
  form_access_key: "test-form-id",
};

/** The manifest images a record gets, through the real sourcing path (no network). */
async function manifestImages(record: BusinessRecord): Promise<ManifestImage[]> {
  const sourced = await sourceImages(record, {
    cacheDir: "/tmp/ss-not-used",
    noImages: false,
    refresh: false,
    onNote: () => {},
  });
  return sourced.images;
}

/** Render the page for a record, exactly as the build does. */
async function page(record: BusinessRecord, images: ManifestImage[]): Promise<{ html: string; ctx: RenderContext }> {
  const form = resolveForm(record);
  const delivery = resolveDelivery(record, form);
  const copy = composeCopy(record, SLUG, form, delivery);
  const ctx: RenderContext = {
    record,
    copy,
    profile: profileFor(record),
    form,
    delivery,
    images,
    slug: SLUG,
    generatedAt: "2026-09-28T00:00:00.000Z",
  };
  return { html: renderIndex(ctx), ctx };
}

test("an AI-generated image is labelled on the page, in a figcaption", async () => {
  const images = await manifestImages({
    ...RECORD,
    images: [
      {
        role: "hero",
        file: "images/hero.jpg",
        license: "AI-generated (labelled fallback - not a photograph of this business)",
        source_url: "",
        author: "gpt-image-1-mini, generated by Site Sourced tooling",
      },
    ],
  });

  expect(isIllustrativeImage(images[0]!)).toBe(true);
  // The manifest says what the image is...
  expect(images[0]!.notes).toContain("AI-generated image used as a fallback");
  expect(images[0]!.notes).toContain("not a photograph of this business");

  const { html, ctx } = await page(RECORD, images);
  const label = illustrationLabel(BUSINESS_NAME);

  // ...and the page says the same thing, in a caption a visitor reads.
  expect(html).toContain(`<figcaption class="wrap muted hero-caption">${esc(label)}</figcaption>`);
  expect(html).toContain("Illustration: this picture was generated by AI as a placeholder");
  expect(html).toContain(`not a photograph of ${BUSINESS_NAME} or of its premises`);
  // The caption is inside a figure, under the hero, and is not hidden from a reader:
  // no inline display/visibility/opacity and no aria-hidden on it.
  const caption = html.slice(html.indexOf("<figcaption"), html.indexOf("</figcaption>"));
  expect(caption).not.toMatch(/display\s*:\s*none|visibility\s*:\s*hidden|opacity\s*:\s*0|aria-hidden/);
  expect(html.indexOf("<figcaption")).toBeGreaterThan(html.indexOf('class="hero'));

  // Nothing else in the self-check complains about this page.
  expect(
    complianceChecks({ html, record: RECORD, copy: ctx.copy, form: ctx.form, delivery: ctx.delivery, images }),
  ).toEqual([]);
});

test("a manifest that records an AI-generated image, with no label on the page, fails the build", async () => {
  const images = await manifestImages({
    ...RECORD,
    images: [
      {
        role: "hero",
        file: "images/hero.jpg",
        license: "AI-generated (labelled fallback - not a photograph of this business)",
        source_url: "",
        author: "gpt-image-1-mini, generated by Site Sourced tooling",
      },
    ],
  });
  const { html, ctx } = await page(RECORD, images);

  // Simulate the page losing its label — what a template edit would do.
  const unlabelled = html.replace(/<figcaption[\s\S]*?<\/figcaption>/g, "");
  expect(unlabelled).not.toContain("generated by AI as a placeholder");

  const problems = complianceChecks({
    html: unlabelled,
    record: RECORD,
    copy: ctx.copy,
    form: ctx.form,
    delivery: ctx.delivery,
    images,
  });
  expect(problems.length).toBeGreaterThan(0);
  expect(problems.join(" ")).toContain("records an AI-generated image");
  expect(problems.join(" ")).toContain("the page carries no label saying so");
  expect(problems.join(" ")).toContain("images/hero.jpg");
});

test("a photograph carries no illustration label", async () => {
  const images = await manifestImages({
    ...RECORD,
    images: [
      {
        role: "hero",
        file: "images/hero.jpg",
        license: "CC0 1.0 (public domain dedication)",
        source_url: "https://example.invalid/photo",
        author: "a photographer",
      },
    ],
  });

  expect(isIllustrativeImage(images[0]!)).toBe(false);
  const { html, ctx } = await page(RECORD, images);
  expect(html).not.toContain("generated by AI as a placeholder");
  expect(html).not.toContain("<figcaption");
  expect(
    complianceChecks({ html, record: RECORD, copy: ctx.copy, form: ctx.form, delivery: ctx.delivery, images }),
  ).toEqual([]);
});
