#!/usr/bin/env bun
/**
 * The claims a generated page makes about itself, and the build's refusal to make
 * one it cannot support.
 *
 *   bun test test/page-claims.test.ts
 *
 * Two of them live here, both enforced by `complianceChecks` in build.ts (the single
 * self-check the build throws on):
 *
 *   1. An AI-generated placeholder must be labelled on the page as an illustration,
 *      not left looking like a photograph of the business. The manifest recording it
 *      is not evidence of a label — the page has to carry one.
 *   2. The phone number and email address printed on a demonstration page are as
 *      published in public listings and were never confirmed with the business, so
 *      they carry the caveat — especially because the demonstration notice sends a
 *      visitor to those very details as the way to reach the business.
 *
 * No filesystem, no network. Fixtures are fictional.
 */
import { expect, test } from "bun:test";

import { complianceChecks } from "../src/demo/build.ts";
import { composeCopy, illustrationLabel, isIllustrativeImage, profileFor } from "../src/demo/copy.ts";
import { resolveDelivery } from "../src/demo/delivery.ts";
import { resolveForm } from "../src/demo/forms.ts";
import { sourceImages } from "../src/demo/images.ts";
import { esc, renderIndex, type RenderContext } from "../src/demo/render.ts";
import type { BusinessRecord, ManifestImage } from "../src/demo/types.ts";

const BUSINESS_NAME = "Example Barber Shop";
const SLUG = "example-barber-shop";

const RECORD: BusinessRecord = {
  name: BUSINESS_NAME,
  category: "Barber shop",
  email: "shop@example-barber.ca",
  form_recipient: "site-sourced-311e0184@ctomail.io",
  form_delivery: "demo",
  form_provider: "formspark",
  form_access_key: "test-form-id",
};

/** The manifest images a record gets, through the real sourcing path (no network). */
async function manifestImages(record: BusinessRecord): Promise<ManifestImage[]> {
  const sourced = await sourceImages(record, {
    cacheDir: "/tmp/ss-not-used",
    noImages: false,
    refresh: false,
    onNote: () => {},
  });
  return sourced.images;
}

/** Render the page for a record, exactly as the build does. */
async function page(record: BusinessRecord, images: ManifestImage[]): Promise<{ html: string; ctx: RenderContext }> {
  const form = resolveForm(record);
  const delivery = resolveDelivery(record, form);
  const copy = composeCopy(record, SLUG, form, delivery);
  const ctx: RenderContext = {
    record,
    copy,
    profile: profileFor(record),
    form,
    delivery,
    images,
    slug: SLUG,
    generatedAt: "2026-09-28T00:00:00.000Z",
  };
  return { html: renderIndex(ctx), ctx };
}

test("an AI-generated image is labelled on the page, in a figcaption", async () => {
  const images = await manifestImages({
    ...RECORD,
    images: [
      {
        role: "hero",
        file: "images/hero.jpg",
        license: "AI-generated (labelled fallback - not a photograph of this business)",
        source_url: "",
        author: "gpt-image-1-mini, generated by Site Sourced tooling",
      },
    ],
  });

  expect(isIllustrativeImage(images[0]!)).toBe(true);
  // The manifest says what the image is...
  expect(images[0]!.notes).toContain("AI-generated image used as a fallback");
  expect(images[0]!.notes).toContain("not a photograph of this business");

  const { html, ctx } = await page(RECORD, images);
  const label = illustrationLabel(BUSINESS_NAME);

  // ...and the page says the same thing, in a caption a visitor reads.
  expect(html).toContain(`<figcaption class="wrap muted hero-caption">${esc(label)}</figcaption>`);
  expect(html).toContain("Illustration: this picture was generated by AI as a placeholder");
  expect(html).toContain(`not a photograph of ${BUSINESS_NAME} or of its premises`);
  // The caption is inside a figure, under the hero, and is not hidden from a reader:
  // no inline display/visibility/opacity and no aria-hidden on it.
  const caption = html.slice(html.indexOf("<figcaption"), html.indexOf("</figcaption>"));
  expect(caption).not.toMatch(/display\s*:\s*none|visibility\s*:\s*hidden|opacity\s*:\s*0|aria-hidden/);
  expect(html.indexOf("<figcaption")).toBeGreaterThan(html.indexOf('class="hero'));

  // Nothing else in the self-check complains about this page.
  expect(
    complianceChecks({ html, record: RECORD, copy: ctx.copy, form: ctx.form, delivery: ctx.delivery, images }),
  ).toEqual([]);
});

test("a manifest that records an AI-generated image, with no label on the page, fails the build", async () => {
  const images = await manifestImages({
    ...RECORD,
    images: [
      {
        role: "hero",
        file: "images/hero.jpg",
        license: "AI-generated (labelled fallback - not a photograph of this business)",
        source_url: "",
        author: "gpt-image-1-mini, generated by Site Sourced tooling",
      },
    ],
  });
  const { html, ctx } = await page(RECORD, images);

  // Simulate the page losing its label — what a template edit would do.
  const unlabelled = html.replace(/<figcaption[\s\S]*?<\/figcaption>/g, "");
  expect(unlabelled).not.toContain("generated by AI as a placeholder");

  const problems = complianceChecks({
    html: unlabelled,
    record: RECORD,
    copy: ctx.copy,
    form: ctx.form,
    delivery: ctx.delivery,
    images,
  });
  expect(problems.length).toBeGreaterThan(0);
  expect(problems.join(" ")).toContain("records an AI-generated image");
  expect(problems.join(" ")).toContain("the page carries no label saying so");
  expect(problems.join(" ")).toContain("images/hero.jpg");
});

test("a photograph carries no illustration label", async () => {
  const images = await manifestImages({
    ...RECORD,
    images: [
      {
        role: "hero",
        file: "images/hero.jpg",
        license: "CC0 1.0 (public domain dedication)",
        source_url: "https://example.invalid/photo",
        author: "a photographer",
      },
    ],
  });

  expect(isIllustrativeImage(images[0]!)).toBe(false);
  const { html, ctx } = await page(RECORD, images);
  expect(html).not.toContain("generated by AI as a placeholder");
  expect(html).not.toContain("<figcaption");
  expect(
    complianceChecks({ html, record: RECORD, copy: ctx.copy, form: ctx.form, delivery: ctx.delivery, images }),
  ).toEqual([]);
});

const CC0 = {
  role: "hero" as const,
  file: "images/hero.jpg",
  license: "CC0 1.0 (public domain dedication)",
  source_url: "https://example.invalid/photo",
  author: "a photographer",
};

test("the details a demonstration points a visitor at carry the published-listings caveat", async () => {
  const images = await manifestImages({ ...RECORD, images: [CC0] });
  const { html, ctx } = await page(RECORD, images);

  expect(ctx.copy.contactCaveat).toContain("as published in public listings — please confirm");
  // Printed twice: with the details in the contact section, and in the footer next to
  // the phone number and email address.
  expect(html.split("as published in public listings — please confirm").length - 1).toBe(2);
  // The demonstration notice points at exactly those details.
  expect(ctx.copy.contactIntro).toContain("use the phone number or email address printed with it");
  expect(
    complianceChecks({ html, record: RECORD, copy: ctx.copy, form: ctx.form, delivery: ctx.delivery, images }),
  ).toEqual([]);

  // A page that prints the details without the caveat fails the build.
  const stripped = html.replace(/as published in public listings[\s\S]*?relying on them\./g, "");
  expect(stripped).not.toContain("as published in public listings");
  const problems = complianceChecks({
    html: stripped,
    record: RECORD,
    copy: ctx.copy,
    form: ctx.form,
    delivery: ctx.delivery,
    images,
  });
  expect(problems.join(" ")).toContain("caveat that belongs with them");
});

test("a delivered page leaves the caveat out", async () => {
  // The client's own address as the recipient: the delivery phase. Their details are
  // their own by then, so the page does not call them unconfirmed.
  const delivered: BusinessRecord = { ...RECORD, form_recipient: RECORD.email!, form_delivery: "business" };
  const images = await manifestImages({ ...delivered, images: [CC0] });
  const { html, ctx } = await page(delivered, images);

  expect(ctx.delivery.mode).toBe("business");
  expect(ctx.copy.contactCaveat).toBe("");
  expect(html).not.toContain("as published in public listings");
  expect(
    complianceChecks({ html, record: delivered, copy: ctx.copy, form: ctx.form, delivery: ctx.delivery, images }),
  ).toEqual([]);
});
